# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        utilisateur:
            entity: 
                class: BlogBundle:User
                property: username
                
    encoders:
        BlogBundle\Entity\User : plaintext
            
    role_hierarchy:
        ROLE_ADMIN:     ROLE_CRITIQUE
        ROLE_CRITIQUE:  ROLE_AUTEUR
        ROLE_AUTEUR:    ROLE_LECTEUR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/(user|theme|article|commentaire|signalementarticle|signalementcom|login_check|logout)
            form_login: 
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /acceuil
                
        accueil:
            pattern: ^/
            anonymous: ~
                
    access_control:
        - { path: ^/(user), roles: ROLE_ADMIN }
        - { path: ^/(theme), roles: ROLE_ADMIN }

        
            
