<?php

namespace BlogBundle\Repository;

/**
 * SignalementArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
