<?php

namespace BlogBundle\Repository;

/**
 * UserThemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserThemesRepository extends \Doctrine\ORM\EntityRepository
{
}
