blog_article:
    resource: "@BlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

blog_commentaire:
    resource: "@BlogBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire

blog_signalementcom:
    resource: "@BlogBundle/Resources/config/routing/signalementcom.yml"
    prefix:   /signalementcom

homepage:
    path:     /homepage
    defaults: { _controller: BlogBundle:Default:index }
    
login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path:     /login_check
    
logout:
    path:     /logout
     
blog_user:
    resource: "@BlogBundle/Resources/config/routing/user.yml"
    prefix:   /user
    
blog_theme:
    resource: "@BlogBundle/Resources/config/routing/theme.yml"
    prefix:   /theme
    
blog_signalementarticle:
    resource: "@BlogBundle/Resources/config/routing/signalementarticle.yml"
    prefix:   /signalementarticle