user_index:
    path:     /
    defaults: { _controller: "BlogBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "BlogBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:User:delete" }
    methods:  DELETE

user_add_article_marque:
    path: /{id}/marqueArticle/{$article}
    defaults: { _controller: "BlogBundle:User:marquerArticle" }

critique_editer_specialites:
    path: /editSpecialite
    defaults: { _controller: "BlogBundle:User:editerSpecialite" }

