user_index:
    path:     /
    defaults: { _controller: "BlogBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "BlogBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:User:delete" }
    methods:  DELETE

user_add_article_marque:
    path: /{id}/marqueArticle/{$article}
    defaults: { _controller: "BlogBundle:User:marquerArticle" }

critique_editer_specialites:
    path: /editSpecialite
    defaults: { _controller: "BlogBundle:User:editerSpecialite" }

profil:
    path:     /profil
    defaults: { _controller: "BlogBundle:User:profil" }
    methods:  [GET, POST]

profil_aime:
    path:     /profil/aime/{id}
    defaults: { _controller: "BlogBundle:User:addUserTheme" }
    methods:  [GET, POST]

profil_specialite:
    path:     /profil/specialite/{id}
    defaults: { _controller: "BlogBundle:User:addSpecialite" }
    methods:  [GET, POST]

profil_aime_pas:
    path:     /profil/aimepas/{id}
    defaults: { _controller: "BlogBundle:User:removeUserTheme" }
    methods:  [GET, POST]

profil_specialite_retrait:
    path:     /profil/retraitspecialite/{id}
    defaults: { _controller: "BlogBundle:User:removeSpecialite" }
    methods:  [GET, POST]
    
user_suppression:
    path:     /delete/{id}
    defaults: { _controller: "BlogBundle:User:deleteUser" }
    methods:  GET