BlogBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
        titre:
            type: string
            length: 255
        dateModif:
            type: date
        datePublication:
            type: date
        active:
            type: boolean
    manyToOne:
        ecritPar:
            targetEntity: User
            mappedBy: article
            cascade: [persist]
    oneToMany:
        comArticle:
            targetEntity: Commentaire
            mappedBy: articleAssocie
        signalement:
            targetEntity: SignalementArticle
            mappedBy: signal
    manyToMany:
        themes:
            targetEntity: Theme
            inversedBy: articles
            cascade: [ persist ]
        marques_par_users:
            targetEntity: User
            inversedBy: articles_marques
