BlogBundle\Entity\Theme:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        active:
            type: boolean
    oneToMany:
        users:
            targetEntity: UserThemes
            mappedBy: aime
    manyToMany:
        articles:
            targetEntity: Article
            mappedBy: themes